/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controlTrafic;

/**
 *
 * @author cmos
 */
public class GaraUI extends javax.swing.JFrame {
    ControlerGara controlerGara=null;
    /**
     * Creates new form GaraUI
     */
    public GaraUI() {
        initComponents();
    }
    
    public GaraUI(ControlerGara cg){
        this.controlerGara = cg;
        initComponents();
    }
    
    
   public void puneTrenPeLinie(int idLinie, Tren t){
       switch (idLinie){
           case 0:
               liniePeron1.setText(t.toString());
               break;
           case 1:
               liniePeron2.setText(t.toString());
               break;
           case 2:
               liniePeron3.setText(t.toString());
               break;
           case 3:
               liniePeron4.setText(t.toString());
               break;
           case 4:
               liniePeron5.setText(t.toString());
               break;
           default:
               break;
       }
   }
   
   public void iaTrenDePeLinie(int idLinie){
        switch (idLinie){
           case 0:
               liniePeron1.setText("");
               break;
           case 1:
               liniePeron2.setText("");
               break;
           case 2:
               liniePeron3.setText("");
               break;
           case 3:
               liniePeron4.setText("");
               break;
           case 4:
               liniePeron5.setText("");
               break;
           default:
               break;
       }
   }
   
   public void schimbaNumeGara (String nume){
       labelNume.setText(nume);
   }
   
   public void scrieLog (String text){
       log.setText(log.getText()+text+"\n");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNume = new javax.swing.JLabel();
        liniePeron1 = new javax.swing.JTextField();
        liniePeron2 = new javax.swing.JTextField();
        liniePeron3 = new javax.swing.JTextField();
        liniePeron4 = new javax.swing.JTextField();
        liniePeron5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNume.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        labelNume.setText("Satu Mare");
        labelNume.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        liniePeron1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liniePeron1ActionPerformed(evt);
            }
        });

        liniePeron2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liniePeron2ActionPerformed(evt);
            }
        });

        liniePeron3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liniePeron3ActionPerformed(evt);
            }
        });

        liniePeron4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liniePeron4ActionPerformed(evt);
            }
        });

        liniePeron5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liniePeron5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Peron");

        jLabel2.setText("Log");

        log.setColumns(20);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelNume, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 492, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(liniePeron5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(liniePeron4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(liniePeron3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(liniePeron2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(liniePeron1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(labelNume, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(77, 77, 77)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(liniePeron1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(liniePeron2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(liniePeron3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(liniePeron4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(liniePeron5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liniePeron1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liniePeron1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liniePeron1ActionPerformed

    private void liniePeron2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liniePeron2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liniePeron2ActionPerformed

    private void liniePeron3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liniePeron3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liniePeron3ActionPerformed

    private void liniePeron4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liniePeron4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liniePeron4ActionPerformed

    private void liniePeron5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liniePeron5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liniePeron5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaraUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNume;
    private javax.swing.JTextField liniePeron1;
    private javax.swing.JTextField liniePeron2;
    private javax.swing.JTextField liniePeron3;
    private javax.swing.JTextField liniePeron4;
    private javax.swing.JTextField liniePeron5;
    private javax.swing.JTextArea log;
    // End of variables declaration//GEN-END:variables
}
